[package]
name = "spike-dasm-rs"
version = "0.1.0"
authors = ["Tynan McAuley"]
edition = "2018"

[[bench]]
name = "dasm"
harness = false

[dependencies]
nom = "6"

[dev-dependencies]
criterion = "0.3"
